spring.application.name=fintrack

# ---------------- DATABASE (Docker) ----------------
spring.datasource.url=jdbc:postgresql://postgres-container:5432/fintrack
spring.datasource.username=postgres
spring.datasource.password=postgres

# ---------------- JPA ----------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ---------------- JWT ----------------
jwt.secret=fintrack_super_secret_key_2026_secure

# ---------------- REDIS (Docker) ----------------
spring.data.redis.host=redis-container
spring.data.redis.port=6379
spring.data.redis.repositories.enabled=false

# ---------------- CACHE LOGGING ----------------
logging.level.org.springframework.cache=TRACE

# ---------------- JACKSON ----------------
spring.jackson.serialization.write-dates-as-timestamps=false

# ---------------- DEBUG (TEMP) ----------------
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
logging.level.org.springframework=DEBUG